// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilitiesHR.Data;

#nullable disable

namespace UtilitiesHR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030101850_AddCutiLimitToEmployee")]
    partial class AddCutiLimitToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UtilitiesHR.Models.Cuti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("JumlahHari")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("date");

                    b.Property<string>("Tujuan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Cutis");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Dinas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Kegiatan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sifat")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalBerangkat")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalPulang")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dinas");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlamatDomisili")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ClusteringIntake")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CutiLimit")
                        .HasColumnType("int");

                    b.Property<string>("EmailPertamina")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Institusi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("IntakeAktif")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IntakePertama")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("JumlahAnak")
                        .HasColumnType("int");

                    b.Property<string>("Jurusan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NamaSuamiIstri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomorHP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorTeleponRumah")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NopegKPI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NopegPersero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PendidikanTerakhir")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusPernikahan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalMPPK")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalPensiun")
                        .HasColumnType("datetime2");

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UkKemejaProduk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UkKemejaPutih")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UkSepatuSafety")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UkWearpack")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NopegKPI");

                    b.HasIndex("NopegPersero")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("UtilitiesHR.Models.MasterSertifikasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MasterSertifikasis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Operator Boiler"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Ahli K3 Umum"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "First Aider"
                        },
                        new
                        {
                            Id = 4,
                            Nama = "Fire Fighting"
                        },
                        new
                        {
                            Id = 5,
                            Nama = "Confined Space"
                        });
                });

            modelBuilder.Entity("UtilitiesHR.Models.Sertifikasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BerlakuDari")
                        .HasColumnType("date");

                    b.Property<DateTime?>("BerlakuSampai")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MasterSertifikasiId")
                        .HasColumnType("int");

                    b.Property<string>("NamaSertifikasi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TanggalMulai")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TanggalSelesai")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MasterSertifikasiId");

                    b.ToTable("Sertifikasis");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Cuti", b =>
                {
                    b.HasOne("UtilitiesHR.Models.Employee", "Employee")
                        .WithMany("CutiList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Dinas", b =>
                {
                    b.HasOne("UtilitiesHR.Models.Employee", "Employee")
                        .WithMany("DinasList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Sertifikasi", b =>
                {
                    b.HasOne("UtilitiesHR.Models.Employee", "Employee")
                        .WithMany("SertifikasiList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilitiesHR.Models.MasterSertifikasi", "MasterSertifikasi")
                        .WithMany()
                        .HasForeignKey("MasterSertifikasiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");

                    b.Navigation("MasterSertifikasi");
                });

            modelBuilder.Entity("UtilitiesHR.Models.Employee", b =>
                {
                    b.Navigation("CutiList");

                    b.Navigation("DinasList");

                    b.Navigation("SertifikasiList");
                });
#pragma warning restore 612, 618
        }
    }
}
